### ISSUE TITLE
Port to Python

### ISSUE THREAD

**Issue by aalhour** [tomstuart/kanren#1]
Hello @tomstuart,

I loved your "Hello, Declarative World!" talk and I loved your microKanren implementation even more. I cloned your repository and I want to port it to Python, do you mind helping me understand some pieces in your code?

Thanks.

**Comment by aalhour** [comment]
Hello @tomstuart,

Never mind, I managed to port the code to Python 3. Thanks a lot for this great repository, it helped me become a better programmer.

I have linked your talk, article and repo at [my ported repo](https://github.com/aalhour/micro_kanren), feel free to pass by and discuss it if you wish :)

Regards,
Ahmad

**Comment by tomstuart** [comment]
Thanks @aalhour! Sorry I dropped the ball on this one — glad you still found it useful.

**Comment by aalhour** [comment]
Hello @tomstuart! Sorry for the late reply, I still find your repo awesome! 😄 

Did you drop the ball on this one because of a personal reason or because you changed your idea about Relational-Declarative programming as a paradigm? If it's the case of the later, then I am really interested hearing your idea(s) on it.

Cheers,
Ahmad
